#pragma once

#define FONT_ICON_FILE_NAME_VS "codicons.ttf"

#define ICON_MIN_VS 0xea60
#define ICON_MAX_16_VS 0xf101
#define ICON_MAX_VS 0xf101
#define ICON_VS_ADD "\xee\xa9\xa0"	// U+EA60
#define ICON_VS_LIGHTBULB "\xee\xa9\xa1"	// U+EA61
#define ICON_VS_REPO "\xee\xa9\xa2"	// U+EA62
#define ICON_VS_REPO_FORKED "\xee\xa9\xa3"	// U+EA63
#define ICON_VS_GIT_PULL_REQUEST "\xee\xa9\xa4"	// U+EA64
#define ICON_VS_RECORD_KEYS "\xee\xa9\xa5"	// U+EA65
#define ICON_VS_TAG "\xee\xa9\xa6"	// U+EA66
#define ICON_VS_PERSON "\xee\xa9\xa7"	// U+EA67
#define ICON_VS_SOURCE_CONTROL "\xee\xa9\xa8"	// U+EA68
#define ICON_VS_MIRROR "\xee\xa9\xa9"	// U+EA69
#define ICON_VS_STAR_EMPTY "\xee\xa9\xaa"	// U+EA6A
#define ICON_VS_COMMENT "\xee\xa9\xab"	// U+EA6B
#define ICON_VS_WARNING "\xee\xa9\xac"	// U+EA6C
#define ICON_VS_SEARCH "\xee\xa9\xad"	// U+EA6D
#define ICON_VS_SIGN_OUT "\xee\xa9\xae"	// U+EA6E
#define ICON_VS_SIGN_IN "\xee\xa9\xaf"	// U+EA6F
#define ICON_VS_EYE "\xee\xa9\xb0"	// U+EA70
#define ICON_VS_CIRCLE_FILLED "\xee\xa9\xb1"	// U+EA71
#define ICON_VS_PRIMITIVE_SQUARE "\xee\xa9\xb2"	// U+EA72
#define ICON_VS_EDIT "\xee\xa9\xb3"	// U+EA73
#define ICON_VS_INFO "\xee\xa9\xb4"	// U+EA74
#define ICON_VS_LOCK "\xee\xa9\xb5"	// U+EA75
#define ICON_VS_CLOSE "\xee\xa9\xb6"	// U+EA76
#define ICON_VS_SYNC "\xee\xa9\xb7"	// U+EA77
#define ICON_VS_DESKTOP_DOWNLOAD "\xee\xa9\xb8"	// U+EA78
#define ICON_VS_BEAKER "\xee\xa9\xb9"	// U+EA79
#define ICON_VS_VM "\xee\xa9\xba"	// U+EA7A
#define ICON_VS_FILE "\xee\xa9\xbb"	// U+EA7B
#define ICON_VS_ELLIPSIS "\xee\xa9\xbc"	// U+EA7C
#define ICON_VS_REPLY "\xee\xa9\xbd"	// U+EA7D
#define ICON_VS_ORGANIZATION "\xee\xa9\xbe"	// U+EA7E
#define ICON_VS_NEW_FILE "\xee\xa9\xbf"	// U+EA7F
#define ICON_VS_NEW_FOLDER "\xee\xaa\x80"	// U+EA80
#define ICON_VS_TRASH "\xee\xaa\x81"	// U+EA81
#define ICON_VS_HISTORY "\xee\xaa\x82"	// U+EA82
#define ICON_VS_FOLDER "\xee\xaa\x83"	// U+EA83
#define ICON_VS_GITHUB "\xee\xaa\x84"	// U+EA84
#define ICON_VS_TERMINAL "\xee\xaa\x85"	// U+EA85
#define ICON_VS_SYMBOL_EVENT "\xee\xaa\x86"	// U+EA86
#define ICON_VS_ERROR "\xee\xaa\x87"	// U+EA87
#define ICON_VS_SYMBOL_VARIABLE "\xee\xaa\x88"	// U+EA88
#define ICON_VS_SYMBOL_ARRAY "\xee\xaa\x8a"	// U+EA8A
#define ICON_VS_SYMBOL_NAMESPACE "\xee\xaa\x8b"	// U+EA8B
#define ICON_VS_SYMBOL_METHOD "\xee\xaa\x8c"	// U+EA8C
#define ICON_VS_SYMBOL_BOOLEAN "\xee\xaa\x8f"	// U+EA8F
#define ICON_VS_SYMBOL_NUMERIC "\xee\xaa\x90"	// U+EA90
#define ICON_VS_SYMBOL_STRUCTURE "\xee\xaa\x91"	// U+EA91
#define ICON_VS_SYMBOL_PARAMETER "\xee\xaa\x92"	// U+EA92
#define ICON_VS_SYMBOL_KEY "\xee\xaa\x93"	// U+EA93
#define ICON_VS_GO_TO_FILE "\xee\xaa\x94"	// U+EA94
#define ICON_VS_SYMBOL_ENUM "\xee\xaa\x95"	// U+EA95
#define ICON_VS_SYMBOL_RULER "\xee\xaa\x96"	// U+EA96
#define ICON_VS_ACTIVATE_BREAKPOINTS "\xee\xaa\x97"	// U+EA97
#define ICON_VS_ARCHIVE "\xee\xaa\x98"	// U+EA98
#define ICON_VS_ARROW_BOTH "\xee\xaa\x99"	// U+EA99
#define ICON_VS_ARROW_DOWN "\xee\xaa\x9a"	// U+EA9A
#define ICON_VS_ARROW_LEFT "\xee\xaa\x9b"	// U+EA9B
#define ICON_VS_ARROW_RIGHT "\xee\xaa\x9c"	// U+EA9C
#define ICON_VS_ARROW_SMALL_DOWN "\xee\xaa\x9d"	// U+EA9D
#define ICON_VS_ARROW_SMALL_LEFT "\xee\xaa\x9e"	// U+EA9E
#define ICON_VS_ARROW_SMALL_RIGHT "\xee\xaa\x9f"	// U+EA9F
#define ICON_VS_ARROW_SMALL_UP "\xee\xaa\xa0"	// U+EAA0
#define ICON_VS_ARROW_UP "\xee\xaa\xa1"	// U+EAA1
#define ICON_VS_BELL "\xee\xaa\xa2"	// U+EAA2
#define ICON_VS_BOLD "\xee\xaa\xa3"	// U+EAA3
#define ICON_VS_BOOK "\xee\xaa\xa4"	// U+EAA4
#define ICON_VS_BOOKMARK "\xee\xaa\xa5"	// U+EAA5
#define ICON_VS_DEBUG_BREAKPOINT_CONDITIONAL_UNVERIFIED "\xee\xaa\xa6"	// U+EAA6
#define ICON_VS_DEBUG_BREAKPOINT_CONDITIONAL "\xee\xaa\xa7"	// U+EAA7
#define ICON_VS_DEBUG_BREAKPOINT_DATA_UNVERIFIED "\xee\xaa\xa8"	// U+EAA8
#define ICON_VS_DEBUG_BREAKPOINT_DATA "\xee\xaa\xa9"	// U+EAA9
#define ICON_VS_DEBUG_BREAKPOINT_LOG_UNVERIFIED "\xee\xaa\xaa"	// U+EAAA
#define ICON_VS_DEBUG_BREAKPOINT_LOG "\xee\xaa\xab"	// U+EAAB
#define ICON_VS_BRIEFCASE "\xee\xaa\xac"	// U+EAAC
#define ICON_VS_BROADCAST "\xee\xaa\xad"	// U+EAAD
#define ICON_VS_BROWSER "\xee\xaa\xae"	// U+EAAE
#define ICON_VS_BUG "\xee\xaa\xaf"	// U+EAAF
#define ICON_VS_CALENDAR "\xee\xaa\xb0"	// U+EAB0
#define ICON_VS_CASE_SENSITIVE "\xee\xaa\xb1"	// U+EAB1
#define ICON_VS_CHECK "\xee\xaa\xb2"	// U+EAB2
#define ICON_VS_CHECKLIST "\xee\xaa\xb3"	// U+EAB3
#define ICON_VS_CHEVRON_DOWN "\xee\xaa\xb4"	// U+EAB4
#define ICON_VS_CHEVRON_LEFT "\xee\xaa\xb5"	// U+EAB5
#define ICON_VS_CHEVRON_RIGHT "\xee\xaa\xb6"	// U+EAB6
#define ICON_VS_CHEVRON_UP "\xee\xaa\xb7"	// U+EAB7
#define ICON_VS_CHROME_CLOSE "\xee\xaa\xb8"	// U+EAB8
#define ICON_VS_CHROME_MAXIMIZE "\xee\xaa\xb9"	// U+EAB9
#define ICON_VS_CHROME_MINIMIZE "\xee\xaa\xba"	// U+EABA
#define ICON_VS_CHROME_RESTORE "\xee\xaa\xbb"	// U+EABB
#define ICON_VS_CIRCLE "\xee\xaa\xbc"	// U+EABC
#define ICON_VS_CIRCLE_SLASH "\xee\xaa\xbd"	// U+EABD
#define ICON_VS_CIRCUIT_BOARD "\xee\xaa\xbe"	// U+EABE
#define ICON_VS_CLEAR_ALL "\xee\xaa\xbf"	// U+EABF
#define ICON_VS_CLIPPY "\xee\xab\x80"	// U+EAC0
#define ICON_VS_CLOSE_ALL "\xee\xab\x81"	// U+EAC1
#define ICON_VS_CLOUD_DOWNLOAD "\xee\xab\x82"	// U+EAC2
#define ICON_VS_CLOUD_UPLOAD "\xee\xab\x83"	// U+EAC3
#define ICON_VS_CODE "\xee\xab\x84"	// U+EAC4
#define ICON_VS_COLLAPSE_ALL "\xee\xab\x85"	// U+EAC5
#define ICON_VS_COLOR_MODE "\xee\xab\x86"	// U+EAC6
#define ICON_VS_COMMENT_DISCUSSION "\xee\xab\x87"	// U+EAC7
#define ICON_VS_CREDIT_CARD "\xee\xab\x89"	// U+EAC9
#define ICON_VS_DASH "\xee\xab\x8c"	// U+EACC
#define ICON_VS_DASHBOARD "\xee\xab\x8d"	// U+EACD
#define ICON_VS_DATABASE "\xee\xab\x8e"	// U+EACE
#define ICON_VS_DEBUG_CONTINUE "\xee\xab\x8f"	// U+EACF
#define ICON_VS_DEBUG_DISCONNECT "\xee\xab\x90"	// U+EAD0
#define ICON_VS_DEBUG_PAUSE "\xee\xab\x91"	// U+EAD1
#define ICON_VS_DEBUG_RESTART "\xee\xab\x92"	// U+EAD2
#define ICON_VS_DEBUG_START "\xee\xab\x93"	// U+EAD3
#define ICON_VS_DEBUG_STEP_INTO "\xee\xab\x94"	// U+EAD4
#define ICON_VS_DEBUG_STEP_OUT "\xee\xab\x95"	// U+EAD5
#define ICON_VS_DEBUG_STEP_OVER "\xee\xab\x96"	// U+EAD6
#define ICON_VS_DEBUG_STOP "\xee\xab\x97"	// U+EAD7
#define ICON_VS_DEBUG "\xee\xab\x98"	// U+EAD8
#define ICON_VS_DEVICE_CAMERA_VIDEO "\xee\xab\x99"	// U+EAD9
#define ICON_VS_DEVICE_CAMERA "\xee\xab\x9a"	// U+EADA
#define ICON_VS_DEVICE_MOBILE "\xee\xab\x9b"	// U+EADB
#define ICON_VS_DIFF_ADDED "\xee\xab\x9c"	// U+EADC
#define ICON_VS_DIFF_IGNORED "\xee\xab\x9d"	// U+EADD
#define ICON_VS_DIFF_MODIFIED "\xee\xab\x9e"	// U+EADE
#define ICON_VS_DIFF_REMOVED "\xee\xab\x9f"	// U+EADF
#define ICON_VS_DIFF_RENAMED "\xee\xab\xa0"	// U+EAE0
#define ICON_VS_DIFF "\xee\xab\xa1"	// U+EAE1
#define ICON_VS_DISCARD "\xee\xab\xa2"	// U+EAE2
#define ICON_VS_EDITOR_LAYOUT "\xee\xab\xa3"	// U+EAE3
#define ICON_VS_EMPTY_WINDOW "\xee\xab\xa4"	// U+EAE4
#define ICON_VS_EXCLUDE "\xee\xab\xa5"	// U+EAE5
#define ICON_VS_EXTENSIONS "\xee\xab\xa6"	// U+EAE6
#define ICON_VS_EYE_CLOSED "\xee\xab\xa7"	// U+EAE7
#define ICON_VS_FILE_BINARY "\xee\xab\xa8"	// U+EAE8
#define ICON_VS_FILE_CODE "\xee\xab\xa9"	// U+EAE9
#define ICON_VS_FILE_MEDIA "\xee\xab\xaa"	// U+EAEA
#define ICON_VS_FILE_PDF "\xee\xab\xab"	// U+EAEB
#define ICON_VS_FILE_SUBMODULE "\xee\xab\xac"	// U+EAEC
#define ICON_VS_FILE_SYMLINK_DIRECTORY "\xee\xab\xad"	// U+EAED
#define ICON_VS_FILE_SYMLINK_FILE "\xee\xab\xae"	// U+EAEE
#define ICON_VS_FILE_ZIP "\xee\xab\xaf"	// U+EAEF
#define ICON_VS_FILES "\xee\xab\xb0"	// U+EAF0
#define ICON_VS_FILTER "\xee\xab\xb1"	// U+EAF1
#define ICON_VS_FLAME "\xee\xab\xb2"	// U+EAF2
#define ICON_VS_FOLD_DOWN "\xee\xab\xb3"	// U+EAF3
#define ICON_VS_FOLD_UP "\xee\xab\xb4"	// U+EAF4
#define ICON_VS_FOLD "\xee\xab\xb5"	// U+EAF5
#define ICON_VS_FOLDER_ACTIVE "\xee\xab\xb6"	// U+EAF6
#define ICON_VS_FOLDER_OPENED "\xee\xab\xb7"	// U+EAF7
#define ICON_VS_GEAR "\xee\xab\xb8"	// U+EAF8
#define ICON_VS_GIFT "\xee\xab\xb9"	// U+EAF9
#define ICON_VS_GIST_SECRET "\xee\xab\xba"	// U+EAFA
#define ICON_VS_GIST "\xee\xab\xbb"	// U+EAFB
#define ICON_VS_GIT_COMMIT "\xee\xab\xbc"	// U+EAFC
#define ICON_VS_GIT_COMPARE "\xee\xab\xbd"	// U+EAFD
#define ICON_VS_GIT_MERGE "\xee\xab\xbe"	// U+EAFE
#define ICON_VS_GITHUB_ACTION "\xee\xab\xbf"	// U+EAFF
#define ICON_VS_GITHUB_ALT "\xee\xac\x80"	// U+EB00
#define ICON_VS_GLOBE "\xee\xac\x81"	// U+EB01
#define ICON_VS_GRABBER "\xee\xac\x82"	// U+EB02
#define ICON_VS_GRAPH "\xee\xac\x83"	// U+EB03
#define ICON_VS_GRIPPER "\xee\xac\x84"	// U+EB04
#define ICON_VS_HEART "\xee\xac\x85"	// U+EB05
#define ICON_VS_HOME "\xee\xac\x86"	// U+EB06
#define ICON_VS_HORIZONTAL_RULE "\xee\xac\x87"	// U+EB07
#define ICON_VS_HUBOT "\xee\xac\x88"	// U+EB08
#define ICON_VS_INBOX "\xee\xac\x89"	// U+EB09
#define ICON_VS_ISSUE_REOPENED "\xee\xac\x8b"	// U+EB0B
#define ICON_VS_ISSUES "\xee\xac\x8c"	// U+EB0C
#define ICON_VS_ITALIC "\xee\xac\x8d"	// U+EB0D
#define ICON_VS_JERSEY "\xee\xac\x8e"	// U+EB0E
#define ICON_VS_JSON "\xee\xac\x8f"	// U+EB0F
#define ICON_VS_KEBAB_VERTICAL "\xee\xac\x90"	// U+EB10
#define ICON_VS_KEY "\xee\xac\x91"	// U+EB11
#define ICON_VS_LAW "\xee\xac\x92"	// U+EB12
#define ICON_VS_LIGHTBULB_AUTOFIX "\xee\xac\x93"	// U+EB13
#define ICON_VS_LINK_EXTERNAL "\xee\xac\x94"	// U+EB14
#define ICON_VS_LINK "\xee\xac\x95"	// U+EB15
#define ICON_VS_LIST_ORDERED "\xee\xac\x96"	// U+EB16
#define ICON_VS_LIST_UNORDERED "\xee\xac\x97"	// U+EB17
#define ICON_VS_LIVE_SHARE "\xee\xac\x98"	// U+EB18
#define ICON_VS_LOADING "\xee\xac\x99"	// U+EB19
#define ICON_VS_LOCATION "\xee\xac\x9a"	// U+EB1A
#define ICON_VS_MAIL_READ "\xee\xac\x9b"	// U+EB1B
#define ICON_VS_MAIL "\xee\xac\x9c"	// U+EB1C
#define ICON_VS_MARKDOWN "\xee\xac\x9d"	// U+EB1D
#define ICON_VS_MEGAPHONE "\xee\xac\x9e"	// U+EB1E
#define ICON_VS_MENTION "\xee\xac\x9f"	// U+EB1F
#define ICON_VS_MILESTONE "\xee\xac\xa0"	// U+EB20
#define ICON_VS_MORTAR_BOARD "\xee\xac\xa1"	// U+EB21
#define ICON_VS_MOVE "\xee\xac\xa2"	// U+EB22
#define ICON_VS_MULTIPLE_WINDOWS "\xee\xac\xa3"	// U+EB23
#define ICON_VS_MUTE "\xee\xac\xa4"	// U+EB24
#define ICON_VS_NO_NEWLINE "\xee\xac\xa5"	// U+EB25
#define ICON_VS_NOTE "\xee\xac\xa6"	// U+EB26
#define ICON_VS_OCTOFACE "\xee\xac\xa7"	// U+EB27
#define ICON_VS_OPEN_PREVIEW "\xee\xac\xa8"	// U+EB28
#define ICON_VS_PACKAGE "\xee\xac\xa9"	// U+EB29
#define ICON_VS_PAINTCAN "\xee\xac\xaa"	// U+EB2A
#define ICON_VS_PIN "\xee\xac\xab"	// U+EB2B
#define ICON_VS_PLAY "\xee\xac\xac"	// U+EB2C
#define ICON_VS_PLUG "\xee\xac\xad"	// U+EB2D
#define ICON_VS_PRESERVE_CASE "\xee\xac\xae"	// U+EB2E
#define ICON_VS_PREVIEW "\xee\xac\xaf"	// U+EB2F
#define ICON_VS_PROJECT "\xee\xac\xb0"	// U+EB30
#define ICON_VS_PULSE "\xee\xac\xb1"	// U+EB31
#define ICON_VS_QUESTION "\xee\xac\xb2"	// U+EB32
#define ICON_VS_QUOTE "\xee\xac\xb3"	// U+EB33
#define ICON_VS_RADIO_TOWER "\xee\xac\xb4"	// U+EB34
#define ICON_VS_REACTIONS "\xee\xac\xb5"	// U+EB35
#define ICON_VS_REFERENCES "\xee\xac\xb6"	// U+EB36
#define ICON_VS_REFRESH "\xee\xac\xb7"	// U+EB37
#define ICON_VS_REGEX "\xee\xac\xb8"	// U+EB38
#define ICON_VS_REMOTE_EXPLORER "\xee\xac\xb9"	// U+EB39
#define ICON_VS_REMOTE "\xee\xac\xba"	// U+EB3A
#define ICON_VS_REMOVE "\xee\xac\xbb"	// U+EB3B
#define ICON_VS_REPLACE_ALL "\xee\xac\xbc"	// U+EB3C
#define ICON_VS_REPLACE "\xee\xac\xbd"	// U+EB3D
#define ICON_VS_REPO_CLONE "\xee\xac\xbe"	// U+EB3E
#define ICON_VS_REPO_FORCE_PUSH "\xee\xac\xbf"	// U+EB3F
#define ICON_VS_REPO_PULL "\xee\xad\x80"	// U+EB40
#define ICON_VS_REPO_PUSH "\xee\xad\x81"	// U+EB41
#define ICON_VS_REPORT "\xee\xad\x82"	// U+EB42
#define ICON_VS_DIFF_SINGLE "\xee\xad\x83"	// U+EB43
#define ICON_VS_ROCKET "\xee\xad\x84"	// U+EB44
#define ICON_VS_ROOT_FOLDER_OPENED "\xee\xad\x85"	// U+EB45
#define ICON_VS_ROOT_FOLDER "\xee\xad\x86"	// U+EB46
#define ICON_VS_RSS "\xee\xad\x87"	// U+EB47
#define ICON_VS_RUBY "\xee\xad\x88"	// U+EB48
#define ICON_VS_SAVE_ALL "\xee\xad\x89"	// U+EB49
#define ICON_VS_SAVE_AS "\xee\xad\x8a"	// U+EB4A
#define ICON_VS_SAVE "\xee\xad\x8b"	// U+EB4B
#define ICON_VS_SCREEN_FULL "\xee\xad\x8c"	// U+EB4C
#define ICON_VS_SCREEN_NORMAL "\xee\xad\x8d"	// U+EB4D
#define ICON_VS_SEARCH_STOP "\xee\xad\x8e"	// U+EB4E
#define ICON_VS_SERVER "\xee\xad\x90"	// U+EB50
#define ICON_VS_SETTINGS_GEAR "\xee\xad\x91"	// U+EB51
#define ICON_VS_SETTINGS "\xee\xad\x92"	// U+EB52
#define ICON_VS_SHIELD "\xee\xad\x93"	// U+EB53
#define ICON_VS_SMILEY "\xee\xad\x94"	// U+EB54
#define ICON_VS_SORT_PRECEDENCE "\xee\xad\x95"	// U+EB55
#define ICON_VS_SPLIT_HORIZONTAL "\xee\xad\x96"	// U+EB56
#define ICON_VS_SPLIT_VERTICAL "\xee\xad\x97"	// U+EB57
#define ICON_VS_SQUIRREL "\xee\xad\x98"	// U+EB58
#define ICON_VS_STAR_FULL "\xee\xad\x99"	// U+EB59
#define ICON_VS_STAR_HALF "\xee\xad\x9a"	// U+EB5A
#define ICON_VS_SYMBOL_CLASS "\xee\xad\x9b"	// U+EB5B
#define ICON_VS_SYMBOL_COLOR "\xee\xad\x9c"	// U+EB5C
#define ICON_VS_SYMBOL_CONSTANT "\xee\xad\x9d"	// U+EB5D
#define ICON_VS_SYMBOL_ENUM_MEMBER "\xee\xad\x9e"	// U+EB5E
#define ICON_VS_SYMBOL_FIELD "\xee\xad\x9f"	// U+EB5F
#define ICON_VS_SYMBOL_INTERFACE "\xee\xad\xa1"	// U+EB61
#define ICON_VS_SYMBOL_KEYWORD "\xee\xad\xa2"	// U+EB62
#define ICON_VS_SYMBOL_MISC "\xee\xad\xa3"	// U+EB63
#define ICON_VS_SYMBOL_OPERATOR "\xee\xad\xa4"	// U+EB64
#define ICON_VS_SYMBOL_PROPERTY "\xee\xad\xa5"	// U+EB65
#define ICON_VS_SYMBOL_SNIPPET "\xee\xad\xa6"	// U+EB66
#define ICON_VS_TASKLIST "\xee\xad\xa7"	// U+EB67
#define ICON_VS_TELESCOPE "\xee\xad\xa8"	// U+EB68
#define ICON_VS_TEXT_SIZE "\xee\xad\xa9"	// U+EB69
#define ICON_VS_THREE_BARS "\xee\xad\xaa"	// U+EB6A
#define ICON_VS_THUMBSDOWN "\xee\xad\xab"	// U+EB6B
#define ICON_VS_THUMBSUP "\xee\xad\xac"	// U+EB6C
#define ICON_VS_TOOLS "\xee\xad\xad"	// U+EB6D
#define ICON_VS_TRIANGLE_DOWN "\xee\xad\xae"	// U+EB6E
#define ICON_VS_TRIANGLE_LEFT "\xee\xad\xaf"	// U+EB6F
#define ICON_VS_TRIANGLE_RIGHT "\xee\xad\xb0"	// U+EB70
#define ICON_VS_TRIANGLE_UP "\xee\xad\xb1"	// U+EB71
#define ICON_VS_TWITTER "\xee\xad\xb2"	// U+EB72
#define ICON_VS_UNFOLD "\xee\xad\xb3"	// U+EB73
#define ICON_VS_UNLOCK "\xee\xad\xb4"	// U+EB74
#define ICON_VS_UNMUTE "\xee\xad\xb5"	// U+EB75
#define ICON_VS_UNVERIFIED "\xee\xad\xb6"	// U+EB76
#define ICON_VS_VERIFIED "\xee\xad\xb7"	// U+EB77
#define ICON_VS_VERSIONS "\xee\xad\xb8"	// U+EB78
#define ICON_VS_VM_ACTIVE "\xee\xad\xb9"	// U+EB79
#define ICON_VS_VM_OUTLINE "\xee\xad\xba"	// U+EB7A
#define ICON_VS_VM_RUNNING "\xee\xad\xbb"	// U+EB7B
#define ICON_VS_WATCH "\xee\xad\xbc"	// U+EB7C
#define ICON_VS_WHITESPACE "\xee\xad\xbd"	// U+EB7D
#define ICON_VS_WHOLE_WORD "\xee\xad\xbe"	// U+EB7E
#define ICON_VS_WINDOW "\xee\xad\xbf"	// U+EB7F
#define ICON_VS_WORD_WRAP "\xee\xae\x80"	// U+EB80
#define ICON_VS_ZOOM_IN "\xee\xae\x81"	// U+EB81
#define ICON_VS_ZOOM_OUT "\xee\xae\x82"	// U+EB82
#define ICON_VS_LIST_FILTER "\xee\xae\x83"	// U+EB83
#define ICON_VS_LIST_FLAT "\xee\xae\x84"	// U+EB84
#define ICON_VS_LIST_SELECTION "\xee\xae\x85"	// U+EB85
#define ICON_VS_LIST_TREE "\xee\xae\x86"	// U+EB86
#define ICON_VS_DEBUG_BREAKPOINT_FUNCTION_UNVERIFIED "\xee\xae\x87"	// U+EB87
#define ICON_VS_DEBUG_BREAKPOINT_FUNCTION "\xee\xae\x88"	// U+EB88
#define ICON_VS_DEBUG_STACKFRAME_ACTIVE "\xee\xae\x89"	// U+EB89
#define ICON_VS_CIRCLE_SMALL_FILLED "\xee\xae\x8a"	// U+EB8A
#define ICON_VS_DEBUG_STACKFRAME "\xee\xae\x8b"	// U+EB8B
#define ICON_VS_DEBUG_BREAKPOINT_UNSUPPORTED "\xee\xae\x8c"	// U+EB8C
#define ICON_VS_SYMBOL_STRING "\xee\xae\x8d"	// U+EB8D
#define ICON_VS_DEBUG_REVERSE_CONTINUE "\xee\xae\x8e"	// U+EB8E
#define ICON_VS_DEBUG_STEP_BACK "\xee\xae\x8f"	// U+EB8F
#define ICON_VS_DEBUG_RESTART_FRAME "\xee\xae\x90"	// U+EB90
#define ICON_VS_DEBUG_ALT "\xee\xae\x91"	// U+EB91
#define ICON_VS_CALL_INCOMING "\xee\xae\x92"	// U+EB92
#define ICON_VS_CALL_OUTGOING "\xee\xae\x93"	// U+EB93
#define ICON_VS_MENU "\xee\xae\x94"	// U+EB94
#define ICON_VS_EXPAND_ALL "\xee\xae\x95"	// U+EB95
#define ICON_VS_FEEDBACK "\xee\xae\x96"	// U+EB96
#define ICON_VS_GROUP_BY_REF_TYPE "\xee\xae\x97"	// U+EB97
#define ICON_VS_UNGROUP_BY_REF_TYPE "\xee\xae\x98"	// U+EB98
#define ICON_VS_ACCOUNT "\xee\xae\x99"	// U+EB99
#define ICON_VS_BELL_DOT "\xee\xae\x9a"	// U+EB9A
#define ICON_VS_DEBUG_CONSOLE "\xee\xae\x9b"	// U+EB9B
#define ICON_VS_LIBRARY "\xee\xae\x9c"	// U+EB9C
#define ICON_VS_OUTPUT "\xee\xae\x9d"	// U+EB9D
#define ICON_VS_RUN_ALL "\xee\xae\x9e"	// U+EB9E
#define ICON_VS_SYNC_IGNORED "\xee\xae\x9f"	// U+EB9F
#define ICON_VS_PINNED "\xee\xae\xa0"	// U+EBA0
#define ICON_VS_GITHUB_INVERTED "\xee\xae\xa1"	// U+EBA1
#define ICON_VS_SERVER_PROCESS "\xee\xae\xa2"	// U+EBA2
#define ICON_VS_SERVER_ENVIRONMENT "\xee\xae\xa3"	// U+EBA3
#define ICON_VS_PASS "\xee\xae\xa4"	// U+EBA4
#define ICON_VS_STOP_CIRCLE "\xee\xae\xa5"	// U+EBA5
#define ICON_VS_PLAY_CIRCLE "\xee\xae\xa6"	// U+EBA6
#define ICON_VS_RECORD "\xee\xae\xa7"	// U+EBA7
#define ICON_VS_DEBUG_ALT_SMALL "\xee\xae\xa8"	// U+EBA8
#define ICON_VS_VM_CONNECT "\xee\xae\xa9"	// U+EBA9
#define ICON_VS_CLOUD "\xee\xae\xaa"	// U+EBAA
#define ICON_VS_MERGE "\xee\xae\xab"	// U+EBAB
#define ICON_VS_EXPORT "\xee\xae\xac"	// U+EBAC
#define ICON_VS_GRAPH_LEFT "\xee\xae\xad"	// U+EBAD
#define ICON_VS_MAGNET "\xee\xae\xae"	// U+EBAE
#define ICON_VS_NOTEBOOK "\xee\xae\xaf"	// U+EBAF
#define ICON_VS_REDO "\xee\xae\xb0"	// U+EBB0
#define ICON_VS_CHECK_ALL "\xee\xae\xb1"	// U+EBB1
#define ICON_VS_PINNED_DIRTY "\xee\xae\xb2"	// U+EBB2
#define ICON_VS_PASS_FILLED "\xee\xae\xb3"	// U+EBB3
#define ICON_VS_CIRCLE_LARGE_FILLED "\xee\xae\xb4"	// U+EBB4
#define ICON_VS_CIRCLE_LARGE "\xee\xae\xb5"	// U+EBB5
#define ICON_VS_COMBINE "\xee\xae\xb6"	// U+EBB6
#define ICON_VS_TABLE "\xee\xae\xb7"	// U+EBB7
#define ICON_VS_VARIABLE_GROUP "\xee\xae\xb8"	// U+EBB8
#define ICON_VS_TYPE_HIERARCHY "\xee\xae\xb9"	// U+EBB9
#define ICON_VS_TYPE_HIERARCHY_SUB "\xee\xae\xba"	// U+EBBA
#define ICON_VS_TYPE_HIERARCHY_SUPER "\xee\xae\xbb"	// U+EBBB
#define ICON_VS_GIT_PULL_REQUEST_CREATE "\xee\xae\xbc"	// U+EBBC
#define ICON_VS_RUN_ABOVE "\xee\xae\xbd"	// U+EBBD
#define ICON_VS_RUN_BELOW "\xee\xae\xbe"	// U+EBBE
#define ICON_VS_NOTEBOOK_TEMPLATE "\xee\xae\xbf"	// U+EBBF
#define ICON_VS_DEBUG_RERUN "\xee\xaf\x80"	// U+EBC0
#define ICON_VS_WORKSPACE_TRUSTED "\xee\xaf\x81"	// U+EBC1
#define ICON_VS_WORKSPACE_UNTRUSTED "\xee\xaf\x82"	// U+EBC2
#define ICON_VS_WORKSPACE_UNKNOWN "\xee\xaf\x83"	// U+EBC3
#define ICON_VS_TERMINAL_CMD "\xee\xaf\x84"	// U+EBC4
#define ICON_VS_TERMINAL_DEBIAN "\xee\xaf\x85"	// U+EBC5
#define ICON_VS_TERMINAL_LINUX "\xee\xaf\x86"	// U+EBC6
#define ICON_VS_TERMINAL_POWERSHELL "\xee\xaf\x87"	// U+EBC7
#define ICON_VS_TERMINAL_TMUX "\xee\xaf\x88"	// U+EBC8
#define ICON_VS_TERMINAL_UBUNTU "\xee\xaf\x89"	// U+EBC9
#define ICON_VS_TERMINAL_BASH "\xee\xaf\x8a"	// U+EBCA
#define ICON_VS_ARROW_SWAP "\xee\xaf\x8b"	// U+EBCB
#define ICON_VS_COPY "\xee\xaf\x8c"	// U+EBCC
#define ICON_VS_PERSON_ADD "\xee\xaf\x8d"	// U+EBCD
#define ICON_VS_FILTER_FILLED "\xee\xaf\x8e"	// U+EBCE
#define ICON_VS_WAND "\xee\xaf\x8f"	// U+EBCF
#define ICON_VS_DEBUG_LINE_BY_LINE "\xee\xaf\x90"	// U+EBD0
#define ICON_VS_INSPECT "\xee\xaf\x91"	// U+EBD1
#define ICON_VS_LAYERS "\xee\xaf\x92"	// U+EBD2
#define ICON_VS_LAYERS_DOT "\xee\xaf\x93"	// U+EBD3
#define ICON_VS_LAYERS_ACTIVE "\xee\xaf\x94"	// U+EBD4
#define ICON_VS_COMPASS "\xee\xaf\x95"	// U+EBD5
#define ICON_VS_COMPASS_DOT "\xee\xaf\x96"	// U+EBD6
#define ICON_VS_COMPASS_ACTIVE "\xee\xaf\x97"	// U+EBD7
#define ICON_VS_AZURE "\xee\xaf\x98"	// U+EBD8
#define ICON_VS_ISSUE_DRAFT "\xee\xaf\x99"	// U+EBD9
#define ICON_VS_GIT_PULL_REQUEST_CLOSED "\xee\xaf\x9a"	// U+EBDA
#define ICON_VS_GIT_PULL_REQUEST_DRAFT "\xee\xaf\x9b"	// U+EBDB
#define ICON_VS_DEBUG_ALL "\xee\xaf\x9c"	// U+EBDC
#define ICON_VS_DEBUG_COVERAGE "\xee\xaf\x9d"	// U+EBDD
#define ICON_VS_RUN_ERRORS "\xee\xaf\x9e"	// U+EBDE
#define ICON_VS_FOLDER_LIBRARY "\xee\xaf\x9f"	// U+EBDF
#define ICON_VS_DEBUG_CONTINUE_SMALL "\xee\xaf\xa0"	// U+EBE0
#define ICON_VS_BEAKER_STOP "\xee\xaf\xa1"	// U+EBE1
#define ICON_VS_GRAPH_LINE "\xee\xaf\xa2"	// U+EBE2
#define ICON_VS_GRAPH_SCATTER "\xee\xaf\xa3"	// U+EBE3
#define ICON_VS_PIE_CHART "\xee\xaf\xa4"	// U+EBE4
#define ICON_VS_BRACKET_DOT "\xee\xaf\xa5"	// U+EBE5
#define ICON_VS_BRACKET_ERROR "\xee\xaf\xa6"	// U+EBE6
#define ICON_VS_LOCK_SMALL "\xee\xaf\xa7"	// U+EBE7
#define ICON_VS_AZURE_DEVOPS "\xee\xaf\xa8"	// U+EBE8
#define ICON_VS_VERIFIED_FILLED "\xee\xaf\xa9"	// U+EBE9
#define ICON_VS_NEWLINE "\xee\xaf\xaa"	// U+EBEA
#define ICON_VS_LAYOUT "\xee\xaf\xab"	// U+EBEB
#define ICON_VS_LAYOUT_ACTIVITYBAR_LEFT "\xee\xaf\xac"	// U+EBEC
#define ICON_VS_LAYOUT_ACTIVITYBAR_RIGHT "\xee\xaf\xad"	// U+EBED
#define ICON_VS_LAYOUT_PANEL_LEFT "\xee\xaf\xae"	// U+EBEE
#define ICON_VS_LAYOUT_PANEL_CENTER "\xee\xaf\xaf"	// U+EBEF
#define ICON_VS_LAYOUT_PANEL_JUSTIFY "\xee\xaf\xb0"	// U+EBF0
#define ICON_VS_LAYOUT_PANEL_RIGHT "\xee\xaf\xb1"	// U+EBF1
#define ICON_VS_LAYOUT_PANEL "\xee\xaf\xb2"	// U+EBF2
#define ICON_VS_LAYOUT_SIDEBAR_LEFT "\xee\xaf\xb3"	// U+EBF3
#define ICON_VS_LAYOUT_SIDEBAR_RIGHT "\xee\xaf\xb4"	// U+EBF4
#define ICON_VS_LAYOUT_STATUSBAR "\xee\xaf\xb5"	// U+EBF5
#define ICON_VS_LAYOUT_MENUBAR "\xee\xaf\xb6"	// U+EBF6
#define ICON_VS_LAYOUT_CENTERED "\xee\xaf\xb7"	// U+EBF7
#define ICON_VS_TARGET "\xee\xaf\xb8"	// U+EBF8
#define ICON_VS_INDENT "\xee\xaf\xb9"	// U+EBF9
#define ICON_VS_RECORD_SMALL "\xee\xaf\xba"	// U+EBFA
#define ICON_VS_ERROR_SMALL "\xee\xaf\xbb"	// U+EBFB
#define ICON_VS_ARROW_CIRCLE_DOWN "\xee\xaf\xbc"	// U+EBFC
#define ICON_VS_ARROW_CIRCLE_LEFT "\xee\xaf\xbd"	// U+EBFD
#define ICON_VS_ARROW_CIRCLE_RIGHT "\xee\xaf\xbe"	// U+EBFE
#define ICON_VS_ARROW_CIRCLE_UP "\xee\xaf\xbf"	// U+EBFF
#define ICON_VS_LAYOUT_SIDEBAR_RIGHT_OFF "\xee\xb0\x80"	// U+EC00
#define ICON_VS_LAYOUT_PANEL_OFF "\xee\xb0\x81"	// U+EC01
#define ICON_VS_LAYOUT_SIDEBAR_LEFT_OFF "\xee\xb0\x82"	// U+EC02
#define ICON_VS_BLANK "\xee\xb0\x83"	// U+EC03
#define ICON_VS_HEART_FILLED "\xee\xb0\x84"	// U+EC04
#define ICON_VS_MAP "\xee\xb0\x85"	// U+EC05
#define ICON_VS_MAP_FILLED "\xee\xb0\x86"	// U+EC06
#define ICON_VS_CIRCLE_SMALL "\xee\xb0\x87"	// U+EC07
#define ICON_VS_BELL_SLASH "\xee\xb0\x88"	// U+EC08
#define ICON_VS_BELL_SLASH_DOT "\xee\xb0\x89"	// U+EC09
#define ICON_VS_COMMENT_UNRESOLVED "\xee\xb0\x8a"	// U+EC0A
#define ICON_VS_GIT_PULL_REQUEST_GO_TO_CHANGES "\xee\xb0\x8b"	// U+EC0B
#define ICON_VS_GIT_PULL_REQUEST_NEW_CHANGES "\xee\xb0\x8c"	// U+EC0C
#define ICON_VS_SEARCH_FUZZY "\xee\xb0\x8d"	// U+EC0D
#define ICON_VS_COMMENT_DRAFT "\xee\xb0\x8e"	// U+EC0E
#define ICON_VS_SEND "\xee\xb0\x8f"	// U+EC0F
#define ICON_VS_SPARKLE "\xee\xb0\x90"	// U+EC10
#define ICON_VS_INSERT "\xee\xb0\x91"	// U+EC11
#define ICON_VS_MIC "\xee\xb0\x92"	// U+EC12
#define ICON_VS_THUMBSDOWN_FILLED "\xee\xb0\x93"	// U+EC13
#define ICON_VS_THUMBSUP_FILLED "\xee\xb0\x94"	// U+EC14
#define ICON_VS_COFFEE "\xee\xb0\x95"	// U+EC15
#define ICON_VS_SNAKE "\xee\xb0\x96"	// U+EC16
#define ICON_VS_GAME "\xee\xb0\x97"	// U+EC17
#define ICON_VS_VR "\xee\xb0\x98"	// U+EC18
#define ICON_VS_CHIP "\xee\xb0\x99"	// U+EC19
#define ICON_VS_PIANO "\xee\xb0\x9a"	// U+EC1A
#define ICON_VS_MUSIC "\xee\xb0\x9b"	// U+EC1B
#define ICON_VS_MIC_FILLED "\xee\xb0\x9c"	// U+EC1C
#define ICON_VS_REPO_FETCH "\xee\xb0\x9d"	// U+EC1D
#define ICON_VS_COPILOT "\xee\xb0\x9e"	// U+EC1E
#define ICON_VS_LIGHTBULB_SPARKLE "\xee\xb0\x9f"	// U+EC1F
#define ICON_VS_ROBOT "\xee\xb0\xa0"	// U+EC20
#define ICON_VS_SPARKLE_FILLED "\xee\xb0\xa1"	// U+EC21
#define ICON_VS_DIFF_MULTIPLE "\xee\xb0\xa3"	// U+EC23
#define ICON_VS_SURROUND_WITH "\xee\xb0\xa4"	// U+EC24
#define ICON_VS_SHARE "\xee\xb0\xa5"	// U+EC25
#define ICON_VS_GIT_STASH "\xee\xb0\xa6"	// U+EC26
#define ICON_VS_GIT_STASH_APPLY "\xee\xb0\xa7"	// U+EC27
#define ICON_VS_GIT_STASH_POP "\xee\xb0\xa8"	// U+EC28
#define ICON_VS_VSCODE "\xee\xb0\xa9"	// U+EC29
#define ICON_VS_VSCODE_INSIDERS "\xee\xb0\xaa"	// U+EC2A
#define ICON_VS_CODE_OSS "\xee\xb0\xab"	// U+EC2B
#define ICON_VS_RUN_COVERAGE "\xee\xb0\xac"	// U+EC2C
#define ICON_VS_RUN_ALL_COVERAGE "\xee\xb0\xad"	// U+EC2D
#define ICON_VS_COVERAGE "\xee\xb0\xae"	// U+EC2E
#define ICON_VS_GITHUB_PROJECT "\xee\xb0\xaf"	// U+EC2F
#define ICON_VS_MAP_VERTICAL "\xee\xb0\xb0"	// U+EC30
#define ICON_VS_MAP_VERTICAL_FILLED "\xee\xb0\xb1"	// U+EC31
#define ICON_VS_GO_TO_SEARCH "\xee\xb0\xb2"	// U+EC32
#define ICON_VS_PERCENTAGE "\xee\xb0\xb3"	// U+EC33
#define ICON_VS_ATTACH "\xee\xb0\xb4"	// U+EC34
#define ICON_VS_GO_TO_EDITING_SESSION "\xee\xb0\xb5"	// U+EC35
#define ICON_VS_EDIT_SESSION "\xee\xb0\xb6"	// U+EC36
#define ICON_VS_CODE_REVIEW "\xee\xb0\xb7"	// U+EC37
#define ICON_VS_COPILOT_WARNING "\xee\xb0\xb8"	// U+EC38
#define ICON_VS_PYTHON "\xee\xb0\xb9"	// U+EC39
#define ICON_VS_COPILOT_LARGE "\xee\xb0\xba"	// U+EC3A
#define ICON_VS_COPILOT_WARNING_LARGE "\xee\xb0\xbb"	// U+EC3B
#define ICON_VS_KEYBOARD_TAB "\xee\xb0\xbc"	// U+EC3C
#define ICON_VS_COPILOT_BLOCKED "\xee\xb0\xbd"	// U+EC3D
#define ICON_VS_COPILOT_NOT_CONNECTED "\xee\xb0\xbe"	// U+EC3E
#define ICON_VS_FLAG "\xee\xb0\xbf"	// U+EC3F
#define ICON_VS_LIGHTBULB_EMPTY "\xee\xb1\x80"	// U+EC40
#define ICON_VS_SYMBOL_METHOD_ARROW "\xee\xb1\x81"	// U+EC41
#define ICON_VS_COPILOT_UNAVAILABLE "\xee\xb1\x82"	// U+EC42
#define ICON_VS_REPO_PINNED "\xee\xb1\x83"	// U+EC43
#define ICON_VS_KEYBOARD_TAB_ABOVE "\xee\xb1\x84"	// U+EC44
#define ICON_VS_KEYBOARD_TAB_BELOW "\xee\xb1\x85"	// U+EC45
#define ICON_VS_GIT_PULL_REQUEST_DONE "\xee\xb1\x86"	// U+EC46
#define ICON_VS_MCP "\xee\xb1\x87"	// U+EC47
#define ICON_VS_EXTENSIONS_LARGE "\xee\xb1\x88"	// U+EC48
#define ICON_VS_LAYOUT_PANEL_DOCK "\xee\xb1\x89"	// U+EC49
#define ICON_VS_LAYOUT_SIDEBAR_LEFT_DOCK "\xee\xb1\x8a"	// U+EC4A
#define ICON_VS_LAYOUT_SIDEBAR_RIGHT_DOCK "\xee\xb1\x8b"	// U+EC4B
#define ICON_VS_COPILOT_IN_PROGRESS "\xee\xb1\x8c"	// U+EC4C
#define ICON_VS_COPILOT_ERROR "\xee\xb1\x8d"	// U+EC4D
#define ICON_VS_COPILOT_SUCCESS "\xee\xb1\x8e"	// U+EC4E
#define ICON_VS_CHAT_SPARKLE "\xee\xb1\x8f"	// U+EC4F
#define ICON_VS_SEARCH_SPARKLE "\xee\xb1\x90"	// U+EC50
#define ICON_VS_EDIT_SPARKLE "\xee\xb1\x91"	// U+EC51
#define ICON_VS_COPILOT_SNOOZE "\xee\xb1\x92"	// U+EC52
#define ICON_VS_SEND_TO_REMOTE_AGENT "\xee\xb1\x93"	// U+EC53
#define ICON_VS_GIT_FETCH "\xef\x84\x81"	// U+F101
