name: Bug Report
description: Something doesn't work correctly in ImHex.
title: "[Bug] "
labels: bug
body:
- type: dropdown
  id: os
  attributes:
    label: Operating System
    description: What Operating System are you using ImHex on?
    options:
      - Windows
      - Linux
      - MacOS
  validations:
    required: true
- type: textarea
  attributes:
    label: What's the issue you encountered?
    description: |
      Describe the issue in detail and what you were doing beforehand.
  validations:
    required: true
- type: textarea
  attributes:
    label: How can the issue be reproduced?
    description: Include a detailed step by step process for recreating your issue.
  validations:
    required: true
- type: input
  attributes:
    label: ImHex Version
    description: |
      The version of ImHex you've been using when encountering the bug. If using a nightly, please add the commit hash as well
    placeholder: X.X.X
  validations:
    required: true
- type: checkboxes
  attributes:
    label: ImHex Build Type
    options:
    - label: Nightly or built from sources
- type: input
  attributes:
    label: Installation type
    description: |
      How did you install ImHex ? MSI/Portable/DMG/AppImage/Fedora package/etc..
  validations:
    required: true
- type: textarea
  attributes:
    label: Additional context?
    placeholder: |
      - Additional information about your environment.
      - If possible and useful, please upload the binary you've been editing when the bug occurred.
  validations:
    required: false
