find_path(CAPSTONE_INCLUDE_DIR capstone.h)
find_library(CAPSTONE_LIBRARY NAMES capstone)

include(FindPackageHandleStandardArgs)

find_package_handle_standard_args(Capstone DEFAULT_MSG CAPSTONE_LIBRARY CAPSTONE_INCLUDE_DIR)

mark_as_advanced(CAPSTONE_INCLUDE_DIR CAPSTONE_LIBRARY)